# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "incubator"
default-run = "incubator"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
crossterm = { workspace = true, features = ["windows"] }
fs-err.workspace = true
fatfs = { workspace = true, features = ["std", "alloc"] }
fscommon.workspace = true
gptman.workspace = true
guid = { workspace = true, features = ["getrandom"] }
futures.workspace = true
futures-concurrency.workspace = true
initrd_cpio.workspace = true
mesh.workspace = true
pal_async.workspace = true
pipette_client.workspace = true
serde = { workspace = true, features = ["derive"] }
tempfile.workspace = true
toml_edit = { workspace = true, features = ["serde"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }

[dev-dependencies]
test_with_tracing.workspace = true

[lints]
workspace = true
