# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "mesh_node"
edition = "2021"
rust-version.workspace = true

[features]
#default = ["std"]
std = ["xrc/std"]

[dependencies]
mesh_derive.workspace = true
mesh_protobuf.workspace = true
open_enum.workspace = true
xrc.workspace = true

futures-channel = { workspace = true, features = ["alloc"] }
getrandom = { workspace = true, features = ["custom"] }
#parking_lot.workspace = true
thiserror.workspace = true
tracing = { version = "0.1", default-features = false }
zerocopy.workspace = true

[target.'cfg(windows)'.dependencies]
pal.workspace = true

[dev-dependencies]
pal_async.workspace = true

test_with_tracing.workspace = true

[lints]
workspace = true
