# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "containerd_shim_openvmm"
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "containerd-shim-openvmm-v2"
path = "src/main.rs"

[dependencies]
containerd_shim_agent_protocol.workspace = true
containerd_shim_protos.workspace = true
guid.workspace = true
mesh.workspace = true
mesh_remote.workspace = true
mesh_rpc.workspace = true
mesh_worker.workspace = true
net_backend_resources.workspace = true
netvsp_resources.workspace = true
openvmm_defs.workspace = true
openvmm_resources = { workspace = true, features = ["virt_kvm", "net_consomme"] }
virtio_resources.workspace = true
unix_socket.workspace = true
pal_async.workspace = true
futures.workspace = true
anyhow.workspace = true
prost.workspace = true
prost-types.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
serial_core.workspace = true
tempfile.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
libc.workspace = true
vm_manifest_builder.workspace = true
vm_resource.workspace = true
vmm_core_defs.workspace = true

[lints]
workspace = true
