# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "vhdx"
edition.workspace = true
rust-version.workspace = true

[dependencies]
bitfield-struct.workspace = true
crc32c.workspace = true
guid.workspace = true
parking_lot = { workspace = true, features = ["arc_lock"] }
thiserror.workspace = true
zerocopy.workspace = true

[dev-dependencies]
pal_async.workspace = true

[lints]
workspace = true
