# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "mesh_channel_core"
edition = "2021"
rust-version.workspace = true

[features]
std = ["mesh_node/std", "xrc/std"]

[dependencies]
mesh_protobuf.workspace = true
mesh_node.workspace = true
xrc.workspace = true

futures-core.workspace = true
thiserror.workspace = true
tracing = { version = "0.1", default-features = false }

[dev-dependencies]
static_assertions.workspace = true
test_with_tracing.workspace = true

futures.workspace = true

[lints]
workspace = true
