# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "vmm_test_container_entrypoint"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
fs-err.workspace = true
vmm_test_images.workspace = true

[lints]
workspace = true
